export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_LOGOUT = "LOGIN_LOGOUT";
export const LOAD_PROFILE = "LOAD_PROFILE";
export const LOG_OUT = "LOG_OUT";

export const HOME_VIDEOS_SUCCESS = "HOME_VIDEOS_SUCCESS";
export const HOME_VIDEOS_FAIL = "HOME_VIDEOS_FAIL";
export const HOME_VIDEOS_REQUEST = "HOME_VIDEOS_REQUEST";

export const VIDEO_DETAILS_SUCCESS = "VIDEO_DETAILS_SUCCESS";
export const VIDEO_DETAILS_FAIL = "VIDEO_DETAILS_FAIL";
export const VIDEO_DETAILS_REQUEST = "VIDEO_DETAILS_REQUEST";

export const CHANNEL_DETAILS_SUCCESS = "CHANNEL_DETAILS_SUCCESS";
export const CHANNEL_DETAILS_FAIL = "CHANNEL_DETAILS_FAIL";
export const CHANNEL_DETAILS_REQUEST = "CHANNEL_DETAILS_REQUEST";

export const COMMENTS_SUCCESS = "COMMENTS_SUCCESS";
export const COMMENTS_FAIL = "COMMENTS_FAIL";
export const COMMENTS_REQUEST = "COMMENTS_REQUEST";

export const SET_SUBSCRIPTION_STATUS = "SET_SUBSCRIPTION_STATUS";

export const RELATED_VIDEOS_SUCCESS = "RELATED_VIDEOS_SUCCESS";
export const RELATED_VIDEOS_FAIL = "RELATED_VIDEOS_FAIL";
export const RELATED_VIDEOS_REQUEST = "RELATED_VIDEOS_REQUEST";
